### ISSUE TITLE
Not working with new Xamarin Studio 6.1

### ISSUE THREAD

**Issue by nbsoftware** [onovotny/SampleXamFormsWithNetStandard#1]
Hello Oren,

Thanks for this sample solution which indeed works on Windows / VS 2015 update 3, I've just verified it.

Alas, it doesn't seem to work anymore with Xamarin Studio 6.1 (just released yesterday).
I get all kind of errors.
Was it working with previous XS 6.0?

It seems that the XamFormsSample portable library fails to build because it is not having the needed references. Trying to add them manually fails too as no package is listed there.

And, the XamFormsSample.iOS fails to reference the XamFormsSample portable library with the error: "Incompatible target framework: .NET Portable, version=v5.0"

Can you confirm?
Should I file a bug to Xamarin?
Is there any temporary workaround?

Thanks

**Comment by clairernovotny** [comment]
I would file a bug with Xamarin. Feel free to cc me if you'd like. I don't regularly use XS, so I'm not sure.

**Comment by nbsoftware** [comment]
I have here https://bugzilla.xamarin.com/show_bug.cgi?id=44494

**Comment by ncarandini** [comment]
The bug has been solved on XS 6.2
This issue can be closed.
